Repository meriam04/emotion-watchers, pull requests merged in 2024-03, with the labels that each got.

#43 Added Cubic Smoothing to Pupillometry Data
  data_processing/data_processing.py
  data_processing/face/crop_and_resize_images.py
  data_processing/face/tests/test_crop_and_resize_images.py
  data_processing/pupil/process_data.py
  data_processing/utils.py
  requirements.txt
Labels: coding

#46 Splitting the Test Set per Individual in Data Processing
  data_processing/data_processing/face/tests/test_separate_images.py
  data_processing/data_processing/process_data.py
Labels: coding, automation

#47 Implemented Training and Testing Pipeline for Pupillometry Model
  data_processing/data_processing/process_data.py
  models/models/face/test.py
  models/models/face/train.py
  models/models/pupil/checkpoints/best_epochs.txt
  models/models/pupil/checkpoints/binary-006.ckpt.data-00000-of-00001
  models/models/pupil/checkpoints/binary-006.ckpt.index
  models/models/pupil/checkpoints/binary.ckpt.data-00000-of-00001
  models/models/pupil/checkpoints/binary.ckpt.index
  models/models/pupil/checkpoints/checkpoint
  models/models/pupil/test.py
  models/models/pupil/train.py
Labels: coding, neural networks

#48 Implemented and Tested Fusion Model
  data_processing/data_processing/process_data.py
  models/models/face/__init__.py
  models/models/face/train.py
  models/models/fusion.py
  models/models/pupil/__init__.py
  models/models/pupil/train.py
Labels: coding, neural networks

#49 Confusion Matrix for Fusion Model
  models/models/confusion_matrix.png
  models/models/fusion.py
Labels: coding, neural networks

#51 Created documentation for data processing and model training/testing
  data_processing/README.md
  data_processing/data_processing/images/crop_ui_example.png
  models/README.md
Labels: documentation
