Repository meriam04/emotion-watchers, pull requests merged in 2024-02, with the labels that each got.

#37 Initial Pupillometry Baseline
  .gitignore
  baseline/face/classifier.py
  baseline/face/confusion_matrix.png
  baseline/face/test.py
  baseline/face/tests/test_files/1_cs_joy.png
  baseline/face/tests/test_train.py
  baseline/face/train.py
  baseline/pupil/__init__.py
  baseline/pupil/classifier.py
  baseline/pupil/train.py
  baseline/pupil/train_keras.py
  data_processing/data_processing.py
  data_processing/face/__init__.py
  data_processing/face/crop_and_resize_images.py
  data_processing/face/tests/__init__.py
  data_processing/face/tests/test_crop_and_resize_images.py
  data_processing/face/tests/test_files/excited_woman.png
  data_processing/face/tests/test_files/happy_man.png
  data_processing/face/tests/test_files/keyboard_cat.mp4
  data_processing/face/tests/test_video_to_images.py
  data_processing/face/video_to_images.py
  data_processing/pupil/PupilDataModel.m
  data_processing/pupil/RawFileModel.m
  data_processing/pupil/RawSamplesModel.m
  data_processing/pupil/ValidSamplesModel.m
  data_processing/pupil/__init__.py
  data_processing/pupil/genMeanDiaSamples.m
  data_processing/pupil/plotSegments.m
  data_processing/pupil/printToConsole.m
  data_processing/pupil/process_data.m
  data_processing/pupil/process_data.py
  data_processing/pupil/rawDataFilter.m
  data_processing/setup.py
  data_processing/tests/test_crop_and_resize_images.py
Labels: bug, environment, coding, experimentation

#40 Prototype for Fusion Model and Data Synchronization
  data_processing/pupil/process_data.m
  models/face/__init__.py
  models/face/tests/test_train.py
  models/face/train.py
  models/fusion.py
  models/pupil/__init__.py
  models/pupil/train.py
  models/setup.py
Labels: coding, neural networks

#39 Automated separation of images by emotion
  .gitignore
  data_processing/data_processing.py
  data_processing/face/tests/test_files/.gitignore
  data_processing/face/tests/test_separate_images.py
Labels: coding, automation

#36 Crop UI
  data_processing/crop_ui.py
Labels: coding, automation
